sonar.issue.ignore.multicriteria=namingMethods,namingFields,namingParameters,namingTypes
sonar.issue.ignore.multicriteria.namingMethods.ruleKey=python:S100
sonar.issue.ignore.multicriteria.namingMethods.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.namingFields.ruleKey=python:S116
sonar.issue.ignore.multicriteria.namingFields.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.namingParameters.ruleKey=python:S117
sonar.issue.ignore.multicriteria.namingParameters.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.namingTypes.ruleKey=python:S1542
sonar.issue.ignore.multicriteria.namingTypes.resourceKey=**/*.py
