#
# This file is part of pysnmp software.
#
# Copyright (c) 2005-2019, Ilya Etingof deceased
#

"""The SNMP engine: what every application is built on.

An `SnmpEngine` owns the engine ID, the message and PDU dispatcher, the
message processing and security models, the MIB instrumentation, and the
transport dispatcher. One engine can serve a manager, an agent, or both.
"""

import os
import shutil
import tempfile
from pathlib import Path
from typing import Any

from pyasn1.type.error import ValueConstraintError

from pysnmp import debug, error
from pysnmp.entity import observer
from pysnmp.proto.acmod import rfc3415, void
from pysnmp.proto.mpmod.rfc2576 import (
    SnmpV1MessageProcessingModel,
    SnmpV2cMessageProcessingModel,
)
from pysnmp.proto.mpmod.rfc3412 import SnmpV3MessageProcessingModel
from pysnmp.proto.rfc3412 import MsgAndPduDispatcher
from pysnmp.proto.secmod.rfc2576 import SnmpV1SecurityModel, SnmpV2cSecurityModel
from pysnmp.proto.secmod.rfc3414 import SnmpUSMSecurityModel

__all__ = ["SnmpEngine"]

#: Environment variable that turns v1/v2c off for every engine in the process.
#:
#: Set it to ``1``, ``true`` or ``yes`` and an ``SnmpEngine`` built without an
#: explicit ``enableLegacyVersions`` speaks SNMPv3 only. It exists so that the
#: policy can be applied to an application that was never written to offer the
#: choice -- which is most of them -- without editing it.
LEGACY_VERSIONS_ENV = "PYSNMP_DISABLE_V1_V2C"

_TRUTHY = frozenset(("1", "true", "yes", "on"))


def _legacyVersionsEnabledByDefault() -> bool:
    """Whether an engine enables v1/v2c when the caller did not say.

    Read on each construction rather than at import, so that a test -- or an
    application that sets the variable while starting up -- gets what the
    environment says now rather than what it said when this module was first
    imported.

    Returns
    -------
        False only when the environment asks for v1/v2c to be off.
    """
    return os.environ.get(LEGACY_VERSIONS_ENV, "").strip().lower() not in _TRUTHY


class SnmpEngine:
    """Creates SNMP engine object.

    SNMP engine object is central in SNMP v3 architecture. It is an umbrella
    object that coordinates interactions between all parts of SNMP v3 system.
    See :RFC:`3412#section-2.1` (where it is termed *The Dispatcher*).

    With PySNMP design, `SnmpEngine` is the only stateful object, all SNMP
    v3 operations require an instance of SNMP engine. Users do not normally
    request services directly from `SnmpEngine`, but pass it around to
    other PySNMP interfaces.

    It is possible to run multiple instances of `SnmpEngine` in the
    application. In a multithreaded environment, each thread that
    works with SNMP must have its own `SnmpEngine` instance.

    Parameters
    ----------
    snmpEngineID : :py:class:`~pysnmp.proto.rfc1902.OctetString`
        Unique and unambiguous identifier of an SNMP engine.
        If not given, `snmpEngineID` is autogenerated and stored on
        the filesystem. See :RFC:`3411#section-3.1.1`  for details.

    enableLegacyVersions : :py:class:`bool`
        Whether this engine speaks SNMPv1 and SNMPv2c at all. When false, the
        v1 and v2c message processing and security models are never
        registered, so an inbound v1 or v2c message is counted in
        `snmpInBadVersions` and dropped, and an outbound one fails with
        `unsupportedMsgProcessingModel`. Defaults to what the
        `PYSNMP_DISABLE_V1_V2C` environment variable says, and to true when it
        says nothing.

    Examples
    --------
    >>> engine = SnmpEngine()
    >>> type(engine.snmpEngineID).__name__
    'SnmpEngineID'
    >>> repr(engine).startswith('SnmpEngine(snmpEngineID=<SnmpEngineID value object')
    True
    >>> v3Only = SnmpEngine(enableLegacyVersions=False)
    >>> sorted(int(x) for x in v3Only.messageProcessingSubsystems)
    [3]
    >>>

    """

    def __init__(
        self,
        snmpEngineID: Any = None,
        maxMessageSize: int = 65507,
        msgAndPduDsp: Any = None,
        enableLegacyVersions: bool | None = None,
    ) -> None:
        """Assemble the subsystems, and settle which SNMP versions this engine speaks.

        `snmpEngineID` defaults to the one the MIB generated for this host, which is
        derived from a MAC address where one can be found. `snmpEngineBoots` is
        incremented here: :RFC:`3414#section-2.2` counts a boot as an engine coming up,
        and USM's time window checks depend on it moving.

        `enableLegacyVersions` decides whether the v1 and v2c message processing and
        security models are registered at all. Leaving them out is the enforcement --
        see the note in the body -- and `None` means take the default from the
        environment.
        """
        self.cache: dict[Any, Any] = {}

        self.observer = observer.MetaObserver()

        if enableLegacyVersions is None:
            enableLegacyVersions = _legacyVersionsEnabledByDefault()

        #: Whether this engine speaks v1/v2c. Read by
        #: :py:mod:`pysnmp.entity.config` so that configuring a community on an
        #: engine that cannot use one fails where the mistake is rather than at
        #: the first send.
        self.enableLegacyVersions = bool(enableLegacyVersions)

        if msgAndPduDsp is None:
            self.msgAndPduDsp = MsgAndPduDispatcher()
        else:
            self.msgAndPduDsp = msgAndPduDsp

        # Omitting the models is the enforcement, and it is deliberately not a
        # check somewhere in the receive path. RFC 3412 section 4.2.1.2 says an
        # unknown msgVersion is counted and dropped, which is what the
        # dispatcher already does for anything it has no model for -- so a v3
        # only engine rejects v1 the same way it rejects a version that does
        # not exist, with no new code on the wire path to get wrong.
        self.messageProcessingSubsystems: dict[Any, Any] = {
            SnmpV3MessageProcessingModel.messageProcessingModelID: SnmpV3MessageProcessingModel(),
        }
        self.securityModels: dict[Any, Any] = {
            SnmpUSMSecurityModel.securityModelID: SnmpUSMSecurityModel(),
        }

        if self.enableLegacyVersions:
            self.messageProcessingSubsystems.update(
                {
                    SnmpV1MessageProcessingModel.messageProcessingModelID: SnmpV1MessageProcessingModel(),
                    SnmpV2cMessageProcessingModel.messageProcessingModelID: SnmpV2cMessageProcessingModel(),
                }
            )
            self.securityModels.update(
                {
                    SnmpV1SecurityModel.securityModelID: SnmpV1SecurityModel(),
                    SnmpV2cSecurityModel.securityModelID: SnmpV2cSecurityModel(),
                }
            )
        self.accessControlModel = {
            void.Vacm.accessModelID: void.Vacm(),
            rfc3415.Vacm.accessModelID: rfc3415.Vacm(),
        }

        self.transportDispatcher = None

        if self.msgAndPduDsp.mibInstrumController is None:
            raise error.PySnmpError("MIB instrumentation does not yet exist")
        (snmpEngineMaxMessageSize,) = (
            self.msgAndPduDsp.mibInstrumController.mibBuilder.importSymbols(
                "__SNMP-FRAMEWORK-MIB", "snmpEngineMaxMessageSize"
            )
        )
        snmpEngineMaxMessageSize.syntax = snmpEngineMaxMessageSize.syntax.clone(
            maxMessageSize
        )
        (snmpEngineBoots,) = (
            self.msgAndPduDsp.mibInstrumController.mibBuilder.importSymbols(
                "__SNMP-FRAMEWORK-MIB", "snmpEngineBoots"
            )
        )
        snmpEngineBoots.syntax += 1
        (origSnmpEngineID,) = (
            self.msgAndPduDsp.mibInstrumController.mibBuilder.importSymbols(
                "__SNMP-FRAMEWORK-MIB", "snmpEngineID"
            )
        )

        if snmpEngineID is None:
            self.snmpEngineID = origSnmpEngineID.syntax
        else:
            origSnmpEngineID.syntax = origSnmpEngineID.syntax.clone(snmpEngineID)
            self.snmpEngineID = origSnmpEngineID.syntax

            debug.logger & debug.flagApp and debug.logger(
                f"SnmpEngine: using custom SNMP Engine ID: {self.snmpEngineID.prettyPrint()}"
            )

            # Attempt to make some of snmp Engine settings persistent.
            # This should probably be generalized as a non-volatile MIB store.

            persistentPath = (
                Path(tempfile.gettempdir())
                / "__pysnmp"
                / self.snmpEngineID.prettyPrint()
            )

            debug.logger & debug.flagApp and debug.logger(
                f"SnmpEngine: using persistent directory: {persistentPath}"
            )

            if not persistentPath.exists():
                try:
                    persistentPath.mkdir(parents=True)
                except OSError:
                    return

            f = persistentPath / "boots"
            try:
                snmpEngineBoots.syntax = snmpEngineBoots.syntax.clone(f.read_text())
            except (OSError, UnicodeDecodeError, ValueConstraintError, ValueError) as e:
                debug.logger & debug.flagApp and debug.logger(
                    f"SnmpEngine: could not load SNMP Engine Boots: {e}"
                )

            try:
                snmpEngineBoots.syntax += 1
            except Exception:  # noqa: BLE001 - the stored counter is whatever was on disk; anything that will not increment restarts it
                snmpEngineBoots.syntax = snmpEngineBoots.syntax.clone(1)

            try:
                fd, fn = tempfile.mkstemp(dir=persistentPath)
                os.write(fd, snmpEngineBoots.syntax.prettyPrint().encode("iso-8859-1"))
                os.close(fd)
                shutil.move(fn, f)
            except Exception as e:  # noqa: BLE001 - persisting the boot counter is best effort; a read-only filesystem must not stop the engine
                debug.logger & debug.flagApp and debug.logger(
                    f"SnmpEngine: could not stored SNMP Engine Boots: {e}"
                )
            else:
                debug.logger & debug.flagApp and debug.logger(
                    f"SnmpEngine: stored SNMP Engine Boots: {snmpEngineBoots.syntax.prettyPrint()}"
                )

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(snmpEngineID={self.snmpEngineID!r})"

    # Transport dispatcher bindings

    def __receiveMessageCbFun(
        self,
        transportDispatcher: Any,
        transportDomain: Any,
        transportAddress: Any,
        wholeMsg: Any,
    ) -> None:
        self.msgAndPduDsp.receiveMessage(
            self, transportDomain, transportAddress, wholeMsg
        )

    def __receiveTimerTickCbFun(self, timeNow: int) -> None:
        self.msgAndPduDsp.receiveTimerTick(self, timeNow)
        for mpHandler in self.messageProcessingSubsystems.values():
            mpHandler.receiveTimerTick(self, timeNow)
        for smHandler in self.securityModels.values():
            smHandler.receiveTimerTick(self, timeNow)

    def registerTransportDispatcher(
        self, transportDispatcher: Any, recvId: Any = None
    ) -> None:
        if (
            self.transportDispatcher is not None
            and self.transportDispatcher is not transportDispatcher
        ):
            raise error.PySnmpError("Transport dispatcher already registered")
        transportDispatcher.registerRecvCbFun(self.__receiveMessageCbFun, recvId)
        if self.transportDispatcher is None:
            transportDispatcher.registerTimerCbFun(self.__receiveTimerTickCbFun)
            self.transportDispatcher = transportDispatcher

    def unregisterTransportDispatcher(self, recvId: Any = None) -> None:
        if self.transportDispatcher is None:
            raise error.PySnmpError("Transport dispatcher not registered")
        self.transportDispatcher.unregisterRecvCbFun(recvId)
        self.transportDispatcher.unregisterTimerCbFun()
        self.transportDispatcher = None

    def getMibBuilder(self) -> Any:
        return self.msgAndPduDsp.mibInstrumController.mibBuilder

    # User app may attach opaque objects to SNMP Engine
    def setUserContext(self, **kwargs: Any) -> None:
        self.cache.update({f"__{k}": kwargs[k] for k in kwargs})

    def getUserContext(self, arg: str) -> Any:
        return self.cache.get(f"__{arg}")

    def delUserContext(self, arg: str) -> None:
        self.cache.pop(f"__{arg}", None)
