#!/usr/bin/env python3
"""Compile an ASN.1 MIB and generate loadable MIB instance stubs."""

from __future__ import annotations

import argparse
import ast
import re
import shutil
import sys
from pathlib import Path
from typing import Any

from pyasn1.type import univ

from pysnmp.proto.rfc1902 import IpAddress

__all__ = [
    "compile_mib",
    "generate_instances",
    "walk_mib_symbols",
]

_MODULE_PATTERN = re.compile(
    r"^\s*([A-Za-z][A-Za-z0-9-]*)\s+(?:PIB-)?DEFINITIONS\s*::=\s*BEGIN",
    re.MULTILINE,
)


def walk_mib_symbols(mibBuilder: Any, modName: str) -> dict[str, dict[str, Any]]:
    """Categorize the managed-object symbols exported by *modName*."""
    result: dict[str, dict[str, Any]] = {
        "scalars": {},
        "table_columns": {},
        "tables": {},
        "table_rows": {},
    }
    if modName not in mibBuilder.mibSymbols:
        return result

    MibScalar, MibTableColumn, MibTable, MibTableRow = mibBuilder.importSymbols(
        "SNMPv2-SMI",
        "MibScalar",
        "MibTableColumn",
        "MibTable",
        "MibTableRow",
    )

    for symName, symObj in mibBuilder.mibSymbols[modName].items():
        # MibTableColumn subclasses MibScalar, so the narrower check must come first.
        if isinstance(symObj, MibTableColumn):
            result["table_columns"][symName] = symObj
        elif isinstance(symObj, MibScalar):
            result["scalars"][symName] = symObj
        elif isinstance(symObj, MibTable):
            result["tables"][symName] = symObj
        elif isinstance(symObj, MibTableRow):
            result["table_rows"][symName] = symObj

    return result


def _candidate_literals(syntax: Any, prefer_nonzero: bool = False):
    """Yield Python literals likely to satisfy an SMI syntax's constraints."""
    if isinstance(syntax, IpAddress):
        yield '"0.0.0.0"'
    elif isinstance(syntax, univ.Integer):
        named_values = getattr(syntax, "namedValues", None)
        if named_values:
            for _name, value in named_values.items():
                yield repr(value)
        for value in (1, 0, -1) if prefer_nonzero else (0, 1, -1):
            yield repr(value)
    elif isinstance(syntax, univ.OctetString):
        yield '""'
        # Cover common lower-bound and fixed-size string constraints.
        for size in range(1, 65):
            yield repr("0" * size)
    elif isinstance(syntax, univ.ObjectIdentifier):
        yield "(0,)"
    elif isinstance(syntax, univ.Null):
        yield "''"


def _default_value_for_syntax(syntax: Any, prefer_nonzero: bool = False) -> str | None:
    """Return a valid placeholder literal, or ``None`` for a schema-only clone."""
    for literal in _candidate_literals(syntax, prefer_nonzero=prefer_nonzero):
        try:
            candidate = syntax.clone(ast.literal_eval(literal))
        except Exception:
            continue
        if candidate.isValue:
            return literal
    return None


def _table_index_suffix(mibBuilder: Any, row: Any) -> tuple[int, ...]:
    """Build a valid sample instance suffix from a MibTableRow index declaration."""
    index_values = []
    for _implied, module_name, symbol_name in row.indexNames:
        (index_object,) = mibBuilder.importSymbols(module_name, symbol_name)
        literal = _default_value_for_syntax(index_object.syntax, prefer_nonzero=True)
        if literal is None:
            return (1,)
        index_values.append(ast.literal_eval(literal))

    try:
        return tuple(row.getInstIdFromIndices(*index_values))
    except Exception:
        return (1,)


def generate_instances(
    mibBuilder: Any,
    modName: str,
    instance_mod_suffix: str = "_instances",
) -> str:
    """Generate a Python MIB instance module for loaded MIB *modName*."""
    symbols = walk_mib_symbols(mibBuilder, modName)
    instance_mod_name = f"{modName}{instance_mod_suffix}"
    objects = sorted(list(symbols["scalars"].items()) + list(symbols["table_columns"].items()))

    lines = [
        "#",
        f"# Generated by mib_instance_generator.py — {instance_mod_name}",
        f"# MIB instance stubs for {modName}",
        "#",
        "(MibScalarInstance,) = mibBuilder.importSymbols(",
        '    "SNMPv2-SMI", "MibScalarInstance"',
        ")",
        "",
    ]

    if objects:
        local_names = [f"_definition_{position}" for position in range(len(objects))]
        lines.append(f"({', '.join(local_names)},) = mibBuilder.importSymbols(")
        lines.append(f"    {modName!r},")
        for symbol_name, _symbol_object in objects:
            lines.append(f"    {symbol_name!r},")
        lines.append(")")
        lines.append("")

    row_suffixes = {
        row.name: _table_index_suffix(mibBuilder, row) for row in symbols["table_rows"].values()
    }
    exported_instances = []

    for position, (symbol_name, symbol_object) in enumerate(objects):
        local_definition = f"_definition_{position}"
        local_instance = f"_instance_{position}"
        if symbol_name in symbols["table_columns"]:
            oid_suffix = row_suffixes.get(symbol_object.name[:-1], (1,))
        else:
            oid_suffix = (0,)

        default_literal = _default_value_for_syntax(symbol_object.syntax)
        clone_expression = (
            f"{local_definition}.syntax.clone({default_literal})"
            if default_literal is not None
            else f"{local_definition}.syntax.clone()"
        )
        lines.append(f"{local_instance} = MibScalarInstance(")
        lines.append(f"    {local_definition}.name, {oid_suffix!r}, {clone_expression}")
        lines.append(")")
        lines.append("")
        exported_instances.append((f"{symbol_name}_inst", local_instance))

    if exported_instances:
        lines.append("mibBuilder.exportSymbols(")
        lines.append(f"    {instance_mod_name!r},")
        lines.append("    **{")
        for export_name, local_instance in exported_instances:
            lines.append(f"        {export_name!r}: {local_instance},")
        lines.append("    },")
        lines.append(")")
    else:
        lines.append(f"mibBuilder.exportSymbols({instance_mod_name!r})")

    lines.append("")
    return "\n".join(lines)


def _module_name_from_asn1(path: Path) -> str:
    source = path.read_text(encoding="utf-8", errors="replace")
    match = _MODULE_PATTERN.search(source)
    if not match:
        raise ValueError(f"could not find an ASN.1 module name in {path}")
    return match.group(1)


def compile_mib(
    mib: str,
    destination: str,
    asn1_sources: list[str] | None = None,
    mib_sources: list[str] | None = None,
) -> tuple[Any, str]:
    """Compile/load *mib* and return its populated builder and module name."""
    from pysnmp.smi.builder import DirMibSource, MibBuilder
    from pysnmp.smi.compiler import addMibCompiler
    from pysnmp.smi.error import MibNotFoundError

    mib_builder = MibBuilder()
    for source in mib_sources or ():
        mib_builder.addMibSources(DirMibSource(source))

    mib_path = Path(mib)
    compiler_sources = list(asn1_sources or ())
    if mib_path.is_file():
        module_name = _module_name_from_asn1(mib_path)
        if mib_path.stem == module_name:
            source_directory = mib_path.resolve().parent
        else:
            # pysmi readers resolve sources by module name, which need not match
            # the filename supplied by the user. Give the compiler a canonical
            # temporary filename without modifying the original source.
            source_directory = Path(destination) / "asn1"
            source_directory.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(mib_path, source_directory / f"{module_name}.txt")
        compiler_sources.insert(0, source_directory.as_uri())
        original_source = mib_path.resolve().parent.as_uri()
        if original_source not in compiler_sources:
            compiler_sources.append(original_source)
    else:
        module_name = mib

    compiler_options: dict[str, Any] = {"destination": destination}
    if compiler_sources:
        compiler_options["sources"] = compiler_sources
    addMibCompiler(mib_builder, **compiler_options)

    if mib_path.is_file():
        compiler = mib_builder.getMibCompiler()
        status = compiler.compile(module_name)
        compiled_files = list(Path(destination).glob(f"{module_name}.py*"))
        if not compiled_files and str(status.get(module_name)) == "untouched":
            # The caller explicitly supplied this source file, so force a
            # rebuild if an installed module with the same name shadowed it.
            status = compiler.compile(module_name, rebuild=True)
            compiled_files = list(Path(destination).glob(f"{module_name}.py*"))

        module_status = status.get(module_name)
        if not compiled_files or str(module_status) in ("failed", "missing", "unprocessed"):
            detail = getattr(module_status, "error", None) or module_status
            raise MibNotFoundError(f"{module_name} compilation failed: {detail}")
        # Ensure a same-named bundled MIB can not shadow the file just compiled.
        compiled_source = DirMibSource(destination)
        mib_builder.setMibSources(compiled_source, *mib_builder.getMibSources())

    mib_builder.loadModules(module_name)
    return mib_builder, module_name


def main() -> int:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(
        description="Compile an ASN.1 MIB and generate MIB instance stubs."
    )
    parser.add_argument("--mib", required=True, help="MIB module name or ASN.1 file path.")
    parser.add_argument("--output", "-o", required=True, help="Output Python module path.")
    parser.add_argument(
        "--asn1-source", action="append", default=None, help="Additional ASN.1 source URL/path."
    )
    parser.add_argument(
        "--mib-source", action="append", default=None, help="Additional compiled MIB path."
    )
    parser.add_argument("--suffix", default="_instances", help="Instance module-name suffix.")
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    try:
        mib_builder, module_name = compile_mib(
            args.mib,
            str(output_path.parent),
            asn1_sources=args.asn1_source,
            mib_sources=args.mib_source,
        )
        source = generate_instances(mib_builder, module_name, instance_mod_suffix=args.suffix)
    except Exception as error:
        print(f"Error processing MIB: {error}", file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8") as output:
        output.write(source)
    print(f"Wrote MIB instances to {output_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
